ALTER TABLE vehicles ADD COLUMN moderation_status VARCHAR(20) DEFAULT 'PENDING';
ALTER TABLE vehicles ADD COLUMN approved_by_id UUID;
ALTER TABLE vehicles ADD COLUMN approved_at TIMESTAMP;
ALTER TABLE vehicles ADD COLUMN rejected_by_id UUID;
ALTER TABLE vehicles ADD COLUMN rejected_at TIMESTAMP;
ALTER TABLE vehicles ADD COLUMN rejection_reason TEXT;
ALTER TABLE vehicles ADD COLUMN published_at TIMESTAMP;
ALTER TABLE vehicles ADD COLUMN views BIGINT DEFAULT 0;
ALTER TABLE vehicles ADD COLUMN favorites_count BIGINT DEFAULT 0;
ALTER TABLE vehicles ADD COLUMN messages_count BIGINT DEFAULT 0;
ALTER TABLE vehicles ADD CONSTRAINT fk_vehicle_approved_by FOREIGN KEY (approved_by_id) REFERENCES users(id);
ALTER TABLE vehicles ADD CONSTRAINT fk_vehicle_rejected_by FOREIGN KEY (rejected_by_id) REFERENCES users(id);
CREATE INDEX idx_vehicles_moderation_status ON vehicles(moderation_status);
CREATE INDEX idx_vehicles_approved_by ON vehicles(approved_by_id);
CREATE INDEX idx_vehicles_rejected_by ON vehicles(rejected_by_id);
CREATE INDEX idx_vehicles_published_at ON vehicles(published_at);
