ALTER TABLE media DROP CONSTRAINT IF EXISTS fk_media_property;
ALTER TABLE media DROP CONSTRAINT IF EXISTS media_property_id_fkey;
ALTER TABLE favorites DROP CONSTRAINT IF EXISTS fk_favorite_property;
ALTER TABLE favorites DROP CONSTRAINT IF EXISTS favorites_property_id_fkey;
ALTER TABLE complaints DROP CONSTRAINT IF EXISTS fk_complaint_reported_property;
ALTER TABLE complaints DROP CONSTRAINT IF EXISTS complaints_reported_property_id_fkey;
ALTER TABLE shared_list_items DROP CONSTRAINT IF EXISTS fk_shared_list_item_property;
ALTER TABLE shared_list_items DROP CONSTRAINT IF EXISTS shared_list_items_property_id_fkey;
ALTER TABLE shared_list_items DROP CONSTRAINT IF EXISTS shared_list_items_list_id_fkey;
ALTER TABLE shared_list_members DROP CONSTRAINT IF EXISTS shared_list_members_list_id_fkey;
ALTER TABLE shared_list_members DROP CONSTRAINT IF EXISTS shared_list_members_user_id_fkey;
ALTER TABLE shared_lists DROP CONSTRAINT IF EXISTS shared_lists_owner_id_fkey;
ALTER TABLE locations DROP CONSTRAINT IF EXISTS locations_property_id_fkey;
ALTER TABLE locations DROP CONSTRAINT IF EXISTS fk_location_property;
ALTER TABLE properties DROP CONSTRAINT IF EXISTS properties_owner_id_fkey;
ALTER TABLE properties DROP CONSTRAINT IF EXISTS fk_property_owner;
ALTER TABLE properties DROP CONSTRAINT IF EXISTS properties_agency_id_fkey;
ALTER TABLE properties DROP CONSTRAINT IF EXISTS fk_property_agency;
ALTER TABLE media DROP COLUMN IF EXISTS property_id;
ALTER TABLE favorites DROP COLUMN IF EXISTS property_id;
ALTER TABLE complaints DROP COLUMN IF EXISTS reported_property_id;
DROP INDEX IF EXISTS idx_complaints_reported_property;
DROP INDEX IF EXISTS unique_user_property;
DROP INDEX IF EXISTS idx_properties_owner;
DROP INDEX IF EXISTS idx_properties_agency;
DROP INDEX IF EXISTS idx_properties_type;
DROP INDEX IF EXISTS idx_properties_status;
DROP INDEX IF EXISTS idx_locations_property;
DROP TABLE IF EXISTS shared_list_items CASCADE;
DROP TABLE IF EXISTS shared_list_members CASCADE;
DROP TABLE IF EXISTS shared_lists CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS properties CASCADE;
